const ROLE_ADMIN = 'ROLE_ADMIN'
const ROLE_CONTRIBUTOR = 'ROLE_CONTRIBUTOR'
const ROLE_EDITOR = 'ROLE_EDITOR'
const ROLE_USER = 'ROLE_USER'

export {
  ROLE_ADMIN,
  ROLE_CONTRIBUTOR,
  ROLE_EDITOR,
  ROLE_USER,
}
