export {
  COMPONENT_TYPE_PACKAGE,
  COMPONENT_TYPE_JOURNAL_INSTANCE,
  COMPONENT_TYPE_BOOK_INSTANCE,
  COMPONENT_TYPE_DATABASE_INSTANCE,
  COMPONENT_TYPE_PLATFORM,
  COMPONENT_TYPE_ORG,
  COMPONENT_TYPE_TIPP,
} from './component-types'
